### ISSUE TITLE
docs around using ollama

### ISSUE THREAD

**Issue by technovangelist** [n8n-io/self-hosted-ai-starter-kit#12]
You mentioned that if using Apple Silicon, you should install ollama on it's own outside of docker. But you don't include a docker-compose yaml for that case. where you don't run ollama in docker.

**Comment by jeanpaul** [comment]
Hi @technovangelist, if you run `docker compose up` without any profile, it will not spin up any ollama for you. You are correct that we could add this to the readme too. Thanks for bringing it up!
